### ISSUE TITLE
TCA0 not listed on Insight for ATtiny412

### ISSUE THREAD

**Issue by ashlynblack** [bloombloombloom/Bloom#113] opened 2024-08-09 01:30 UTC
Issue reported via Bloom Insight.
Target name: ATtiny412
Target ID: 0x1e9223
Target variant: ATtiny412-SSFR

Please describe your issue below. Include as much detail as possible.

There is no register listing for TCA0 on Insight. TCB0 and TCD0 are listed but TCA0 is not.

**Comment by ashlynblack** [comment] 2024-08-09 03:10
Just seen the other issues for TCA0, can close this if you want.

**Comment by navnavnav** [comment] 2024-08-09 17:10
Closed this as a duplicate of https://github.com/bloombloombloom/Bloom/issues/111

**Closed** 2024-08-09 17:10 UTC
